## 其他作者库同理  替换如下    
 
## 作者名         6Svip120apk69  
## 作者库名       gitee_q8qsTAUA_cThxc1RBVUE     
## 作者分支名     main     
## 同步分支名     ZIYE   （可自定义 ）




name: wuzhi-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: MyActions_MyActions
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync MyActions_MyActions
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wuzhi01/MyActions.git"
          source_branch: "main"
          destination_branch: "JDJD"
          github_token: ${{ secrets.PAT }}
